### ISSUE TITLE
blackbox-render: More options

### ISSUE THREAD

**Issue by 19Gerhard85** [cleanflight/blackbox-tools#13]
A few more options would be nice:
- [ ] Hide "Batt. cell" (bottom left corner)
- [ ] Hide "Acceleration" (bottom left corner)
- [ ] Change colors

**Comment by thenickdude** [comment]
Until those features are added, you might enjoy the Web browser based renderer instead, which doesn't render that information and has recently gained the capability for video export in .webm format:

https://chrome.google.com/webstore/detail/cleanflight-blackbox-expl/cahpidddaimdojnddnahjpnefajpheep?hl=en

**Comment by 19Gerhard85** [comment]
@thenickdude Thanks for the hint, I tried that but Chrome app outputs only webm format and have problems with very large files.
