### ISSUE TITLE
Decode does not work with new betaflight .BFL file format

### ISSUE THREAD

**Issue by goatspoon** [cleanflight/blackbox-tools#17]

**Comment by thenickdude** [comment]
Really? My understanding was that Betaflight has kept the logs compatible. Do you have an example log file I can try?

**Comment by goatspoon** [comment]
It does surprise me too. I managed to get a partial decode using --raw and by editing the file. But it still doesnt give a correct decode. https://www.dropbox.com/s/fufbfwpwighvhg2/LOG00004.BFL?dl=0

**Comment by thenickdude** [comment]
Ah, it's due to this new predictor they added:

https://github.com/betaflight/betaflight/commit/70542eabd05319232470d1a1e2700c6083b1a96a

I'll add support for it.

**Comment by goatspoon** [comment]
Very much appreciated.

**Comment by thenickdude** [comment]
Please try out the new version 0.4.3, it should support your log now:

https://github.com/cleanflight/blackbox-tools/releases/tag/v0.4.3

**Comment by goatspoon** [comment]
Still getting "Unsupported field predictor 11"

https://www.dropbox.com/s/l4n0moqmkl0dwbv/LOG00004.BFL?dl=0

**Comment by thenickdude** [comment]
Ah I didn't rebuild the Windows binary! One second, I'll rebuild that and reupload.

**Comment by thenickdude** [comment]
Please download the release again and give it another go!

**Comment by goatspoon** [comment]
Perfect, thanks for your help. to EXCEL!
