### ISSUE TITLE
New feature, 3 Axis G meter

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/blackbox-tools#2]
It would be neat to have a 3 axis G meter. A peak hold indicator would be nice also. The most I have hit was 2.8 G's with KK2.0, F330. Thanks guys, BB is great!

**Comment by thenickdude** [comment]
I'm assuming you mean for the web-based log viewer? Please add your feature request to that repository instead:

https://github.com/cleanflight/blackbox-log-viewer/issues/new

(it turns out that the lateral G's aren't very interesting because the quadcopter can only thrust vertically)
