### ISSUE TITLE
Dashware 

### ISSUE THREAD

**Issue by Yamaford** [cleanflight/blackbox-tools#20]
Nick,
Is there any tools available to convert the current blackbox log to something Dashware can read? I couldn't get the old tools to open.

This is from the FAQ on dashware.net
I want to make my own data file. How can I make it work with DashWare?
Here are some notes on making a DashWare-friendly CSV data file:

-It’s good to have a static line of text at the top declaring that it is your data format. Something like “Some Cool Logger Data File”. The DashWare Data Profile for your format can then be easily set up to automatically detect one of your data files.
-We require a CSV header line: A line of text containing the column headers/names.
-Then the raw data lines would follow after that.
-There should be a Time column (full timestamps work great, e.g. “2011/08/07 20:10:02.200”, or the total running time in seconds e.g. “1.1”)
-Latitude and Longitude should be in +/- decimal degrees
-Be consistent with your data units, or at least change the column name when you use different units. DashWare can be used to create calculated data columns for other units.

You will then need to make a Data Profile that understands your format. Bring up the Data Profile Editor (File Menu > Edit Data Profiles…) and press F1 for detailed help. Tips:
-The column mappings (bottom right area of dialog) are used to map your column names to known DashWare data types. Set up the mapping for your time column first, so you can use the “Test File / View Data…” button. It is very handy. “ / Data Running Time, Seconds” is the mapping you need.
-To get a map to show up, you need to use our “Degrees to Cartesian Converter” (calculators/converters are in the bottom left area of dialog) to create X and Y units in feet. You must map these new X and Y output columns to our “Positional \ Longitude / X Position (Feet)” and “Positional \ Latitude / Y Position (Feet)” data types.

Have a look at an existing data profile, such as the GPX one, as an example.

**Comment by GhostRiderRC** [comment]
you can use blackbox tools to convert to csv and gpx. gpx already has a lot of useful info like alt, gs, heading and ofcourse the map of your flightpath

**Comment by xsnoopy** [comment]
@Yamaford I worked on a complete set up/ workflow to convert blackbox to dashware. In my repository you'll find the dashware gauges, templates and data profile. I used python to convert it. I try to implement that in the regular code, but can't find a lot documentation on it. It'll take some time until I understand how that all works in decode and render.

https://github.com/xsnoopy/bfbbl2dashware
