### ISSUE TITLE
not able to run program 

### ISSUE THREAD

**Issue by Ipoc78** [cleanflight/blackbox-tools#26]
When i click on the application, the window pops up but then goes away, not sure what going on here

**Comment by thenickdude** [comment]
It's a command line program, you need to run it from the Windows command
prompt.

**Comment by Ipoc78** [comment]
"If you're using Windows, you can drag and drop your log files onto blackbox_decode and they'll all be decoded"

My apologies for not understanding how to use this,
But my assumption is is I grab the file and drop it in over the top of blackbox_decode
Again a window pops up and then disappears.

I can go to the command line drag blackbox_decode into cmd.

From there I will get this(see below) but I am uncertain how to  actually  load a txt file for decoding

Again apologies for not understanding and thank you for the help

"CUsage:
     blackbox_decode [options] <input logs>

Options:
   --help                   This page
   --index <num>            Choose the log from the file that should be decoded (or omit to decode all)
   --limits                 Print the limits and range of each field
   --stdout                 Write log to stdout instead of to a file
   --unit-amperage <unit>   Current meter unit (raw|mA|A), default is A (amps)
   --unit-frame-time <unit> Frame timestamp unit (us|s), default is us (microseconds)
   --unit-height <unit>     Height unit (m|cm|ft), default is cm (centimeters)
   --unit-rotation <unit>   Rate of rotation unit (raw|deg/s|rad/s), default is raw
   --unit-acceleration <u>  Acceleration unit (raw|g|m/s2), default is raw
   --unit-gps-speed <unit>  GPS speed unit (mps|kph|mph), default is mps (meters per second)
   --unit-vbat <unit>       Vbat unit (raw|mV|V), default is V (volts)
   --merge-gps              Merge GPS data into the main CSV log file instead of writing it separately
   --simulate-current-meter Simulate a virtual current meter using throttle data
   --sim-current-meter-scale   Override the FC's settings for the current meter simulation
   --sim-current-meter-offset  Override the FC's settings for the current meter simulation
   --simulate-imu           Compute tilt/roll/heading fields from gyro/accel/mag data
   --imu-ignore-mag         Ignore magnetometer data when computing heading
   --declination <val>      Set magnetic declination in degrees.minutes format (e.g. -12.58 for New York)
   --declination-dec <val>  Set magnetic declination in decimal degrees (e.g. -12.97 for New York)
   --debug                  Show extra debugging information
   --raw                    Don't apply"
