### ISSUE TITLE
compute PID error and RC rate

### ISSUE THREAD

**Issue by bw1129** [cleanflight/blackbox-tools#29]
blackbox_decode does not compute RC rate and PID error (for anyone interested in doing offline analyses on these). My current workaround is to load the log in explorer and save an csv file from there which contains these variables, so presumably they are computed in explorer. I am trying to do offline Matlab analyses on PID error, and it'd be less cumbersome, and easier to implement within Matlab scripts, if blackbox_decode did this.

**Comment by mikeller** [comment]
@bw1129: Feel free to open a pull request for adding this to the blackbox tools. :-)
