### ISSUE TITLE
Feature Request: Output Tuning Values to Text File from blackbox_decode 

### ISSUE THREAD

**Issue by AndersonRayner** [cleanflight/blackbox-tools#30]
When decoding log files from blackbox_decode it would be great if the PID tuning values used during that log were output to a text file (rather than having to keep a manual log for optimising tuning).  I think they're already decoded as part of blackbox_render but that makes it difficult to batch-analyse files

**Comment by mikeller** [comment]
@AndersonRayner: Try opening this feature request in https://github.com/betaflight/blackbox-tools/issues - it's got a better chance of being picked up there.

**Comment by AndersonRayner** [comment]
Thanks, I've opened the feature request over in betaflight.
