### ISSUE TITLE
Missing field encoding header for field #0 'GPS_fixType'

### ISSUE THREAD

**Issue by jacoues** [cleanflight/blackbox-tools#33]
Hi all, I am running a Lumenier F7 dual gyro f7 controller with the Matek F422SE firmware on INAV. I recorded a flight using the blackbox logger with a Beitian 880 GPS and compass module and tried to view the log. The explorer is unable to parse the data and returns the following error:
Missing field encoding header for field #0 'GPS_fixType' 

WIth Blackbox decode tools I was able to get three files out, but they are very short and do not contain the logs.

**Comment by stronnag** [comment]
For inav, you should use the inav blackbox tools.

https://github.com/iNavFlight/blackbox-tools
https://github.com/iNavFlight/blackbox-log-viewer
