### ISSUE TITLE
Use blackbox_decode with a .csv file

### ISSUE THREAD

**Issue by julienguegan** [cleanflight/blackbox-tools#34]
The log file produce by my Taranis is already a .csv file but I still want to be able to produce a .gpx file with the tool for displaying gps data on google earth. 

But I can't figure how to make it work as the tool requires a .txt file ...

**Comment by julienguegan** [comment]
(I have the error "Couldn't find the header of a flight log in the file [...], is this the right kind of file?" when directly using the .csv log file and the .csv converted in .txt file)

**Comment by McGiverGim** [comment]
This is not for Taranis files, this is for Betaflight blackbox files.

**Comment by julienguegan** [comment]
Ok my bad, I managed it by using https://www.gpsvisualizer.com/
