### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by LaserLock** [cleanflight/blackbox-tools#9]
i got this error on 2 different logs, the decode had no errors. 
other index on the same log worked.
why do i get it and how i prevent it in the future?

(i use a mac-mini with osx 10.10.4 and the tools 0.4.1)

**Comment by thenickdude** [comment]
Please email me your log file ( n.sherlock@gmail.com ), or upload it somewhere where I can download it.

**Comment by LaserLock** [comment]
sure ;)

http://rc-team-austria.com/uploads/LOG00006.TXT - index 2
http://rc-team-austria.com/uploads/LOG00009.TXT - index 1

**Comment by thenickdude** [comment]
This looks to be a bug in the Cairo drawing library which is fixed in a newer version of Cairo. I'll get a new version of blackbox_render built that includes the fix and let you know!

**Comment by thenickdude** [comment]
Fixed in fc67b11c7352e3b0599a16afc709ed49bc241a93, please grab this new release:

https://github.com/cleanflight/blackbox-tools/releases/tag/v0.4.1.1
